-- Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS coffee_machines (
    id SERIAL PRIMARY KEY,
    brand VARCHAR(255),
    model VARCHAR(255),
    price DECIMAL,
    water_tank_capacity INT,
    milk_tank_capacity INT,
    coffee_bean_capacity INT
);
CREATE TABLE IF NOT EXISTS users (
    id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username VARCHAR(255) UNIQUE,
    password VARCHAR(255),
    status VARCHAR(10) CHECK (status IN ('ROLE_USER', 'ROLE_ADMIN'))
);
-- Insert sample data
INSERT INTO coffee_machines (brand, model, price, water_tank_capacity, milk_tank_capacity, coffee_bean_capacity)
VALUES
    ('DeLonghi', 'Magnifica S', 29999, 1800, 600, 250),
    ('Philips', 'Series 3200', 33999, 1500, 250, 275),
    ('Nespresso', 'Pixie', 8499, 700, 0, 100),
    ('Breville', 'Barista Express', 54999, 2000, 500, 225),
    ('Jura', 'E6', 79999, 1500, 400, 280),
    ('Krups', 'Evidence', 43999, 2000, 600, 260),
    ('Saeco', 'Xelsis', 94999, 1700, 500, 300),
    ('Bosch', 'Tassimo', 3499, 900, 0, 150);
